import { spawn } from 'node:child_process';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { pgConnectionEnv } from '../../src/services/backup/postgresBackup';

/**
 * Write prisma/migrations/0_baseline/migration.sql — the schema of the Railway
 * database as it stands, as the first entry in Prisma's migration history.
 *
 *   pnpm db:baseline
 *
 * WHY. The 149 migrations that built this schema were written for Supabase:
 * they grant to its roles, create policies for its REST endpoint and reach into
 * its `auth` schema, and several cannot run on a plain Postgres at all. The
 * database on Railway was not built by replaying them — it was copied. So its
 * history starts here: one migration that IS the copied schema, marked as
 * already applied, and every change after it a new migration on top.
 *
 *   pnpm db:baseline                                          once, after the copy
 *   pnpm exec prisma migrate resolve --applied 0_baseline     tell Prisma it is already there
 *   pnpm exec prisma migrate deploy                           from then on: apply what is new
 *
 * (The last two connect with DIRECT_DATABASE_URL, which by then is the Railway
 * administrator URL. See infra/railway/README.md.)
 *
 * A NEW MIGRATION is a folder `prisma/migrations/<yyyymmddhhmmss>_<name>/`
 * holding a hand-written `migration.sql`. Never `prisma migrate dev` and never
 * `prisma db push`: both make the database match prisma/schema.prisma, which
 * cannot express the functions and triggers this application depends on, and
 * would remove them.
 *
 * READ ONLY against the database: the only thing run is `pg_dump --schema-only`.
 *
 * REBUILDING A DATABASE FROM NOTHING is bootstrap.sql, then this file, then
 * post-restore.sql — the first makes the roles and extensions the schema
 * names, the last grants the API its access.
 */

function pgDump(env: Record<string, string>): Promise<string> {
  return new Promise((resolve, reject) => {
    const child = spawn(
      'pg_dump',
      ['--schema-only', '--no-owner', '--no-privileges', '--no-publications', '--no-subscriptions',
        '--schema=public', '--schema=app', '--exclude-table=public._prisma_migrations'],
      { env: { ...process.env, ...env }, stdio: ['ignore', 'pipe', 'pipe'] },
    );
    let out = '';
    let err = '';
    child.stdout.on('data', (c: Buffer) => { out += c.toString('utf8'); });
    child.stderr.on('data', (c: Buffer) => { err += c.toString('utf8'); });
    child.on('error', (e) => reject(new Error(`could not start pg_dump: ${e.message}`)));
    child.on('close', (code) => {
      if (code === 0) return resolve(out);
      reject(new Error(`pg_dump failed (exit ${code}): ${err.trim().split('\n').slice(-4).join(' | ').split(env.PGPASSWORD || '\u0000').join('***')}`));
    });
  });
}

async function main() {
  const url = (process.env.RAILWAY_DB_URL || '').trim();
  if (!url) throw new Error('RAILWAY_DB_URL is required — the Railway administrator connection string');
  const env = pgConnectionEnv(url);
  if (!new URL(url).searchParams.get('sslmode')) env.PGSSLMODE = 'prefer';
  if (/supabase/i.test(env.PGHOST)) {
    throw new Error('RAILWAY_DB_URL points at Supabase. The baseline is the schema of the COPY — the one without Supabase\'s pieces.');
  }

  const dump = await pgDump(env);
  const sql = dump
    .split('\n')
    // psql meta-commands (pg_dump 18 brackets its output with \restrict); Prisma
    // sends the file to the server as SQL, where a backslash command is an error.
    .filter((line) => !line.startsWith('\\'))
    // bootstrap.sql makes both schemas — `app` before pg_trgm can be installed
    // beside it, `public` because every database has one.
    .filter((line) => !/^CREATE SCHEMA (public|app);$/.test(line))
    .join('\n');

  const dir = path.join(__dirname, '..', '..', 'prisma', 'migrations');
  await mkdir(path.join(dir, '0_baseline'), { recursive: true });
  await writeFile(
    path.join(dir, '0_baseline', 'migration.sql'),
    `-- The schema of the database at the moment it went into service, written by\n-- \`pnpm db:baseline\`. Already applied to that database: mark it so with\n-- \`prisma migrate resolve --applied 0_baseline\`. Do not edit — changes are new\n-- migrations. Building a database from nothing: bootstrap.sql, this, post-restore.sql.\n\n${sql}`,
  );
  await writeFile(
    path.join(dir, 'migration_lock.toml'),
    '# Please do not edit this file manually\n# It should be added in your version-control system (e.g., Git)\nprovider = "postgresql"\n',
  );

  const count = (re: RegExp) => (sql.match(re) ?? []).length;
  console.log(
    `[db:baseline] ${env.PGHOST}/${env.PGDATABASE}: ${count(/^CREATE TABLE /gm)} tables, ${count(/^CREATE FUNCTION /gm)} functions, ` +
      `${count(/^CREATE TRIGGER /gm)} triggers, ${count(/^CREATE TYPE /gm)} types → prisma/migrations/0_baseline/migration.sql`,
  );
  console.log('[db:baseline] next: pnpm exec prisma migrate resolve --applied 0_baseline');
}

main().catch((err) => {
  console.error('[db:baseline]', err instanceof Error ? err.message : err);
  process.exit(1);
});
